### ISSUE TITLE
Creating trigger animation

### ISSUE THREAD

**Issue by tobe-sta** [Dillion/iOS-Flip-Transform#10]
I'm attempting to put a triggered animation in my project, but running into a few problems. I am currently trying to modify the panned: recogniser, but is the trigger animation much simpler than the controlled?

Also, does it require two different tap recognisers for both forward and backwards animation? Otherwise how does it know which to play?

Thanks.

**Comment by Dillion** [comment]
Just think of the controlled animation as a continuous state that only terminates when you reach the boundaries of the rotation, which is why it needs to be matched with a continuous gesture recognizer like panned:

You can set the direction of the animation in the delegate and it should update accordingly
